### ISSUE TITLE
Nil reference exception when processes return a nil result from Start()

### ISSUE THREAD

**Issue by aphistic** [efritz/nacelle#8]
```
[2018-02-20 18:59:45.990]  INFO Stopped AWS Server process caller=awsserver/awsserver.go:218
[2018-02-20 18:59:45.991]  INFO unnamed process has stopped cleanly, starting graceful shutdown caller=nacelle/runner.go:282
[2018-02-20 18:59:45.991] DEBUG Stopping processes at priority 0 caller=nacelle/runner.go:326
[2018-02-20 18:59:45.991] DEBUG Stopping unnamed process caller=nacelle/runner.go:329
[2018-02-20 18:59:45.991] DEBUG Stopping unnamed process caller=nacelle/runner.go:329
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f9575]

goroutine 1 [running]:
github.com/mitel-networks/platform-api-mediaservices-video/mitel-supervisor/vendor/github.com/efritz/nacelle.(*Bootstrapper).boot(0xc4201774d0, 0x0)
	/go/src/github.com/mitel-networks/platform-api-mediaservices-video/mitel-supervisor/vendor/github.com/efritz/nacelle/boot.go:119 +0xd85
github.com/mitel-networks/platform-api-mediaservices-video/mitel-supervisor/vendor/github.com/efritz/nacelle.(*Bootstrapper).Boot(0xc4201774d0)
	/go/src/github.com/mitel-networks/platform-api-mediaservices-video/mitel-supervisor/vendor/github.com/efritz/nacelle/boot.go:57 +0x2b
main.RunAws()
	/go/src/github.com/mitel-networks/platform-api-mediaservices-video/mitel-supervisor/aws.go:26 +0x1a8
main.main()
	/go/src/github.com/mitel-networks/platform-api-mediaservices-video/mitel-supervisor/main.go:42 +0x7e0
```

**Comment by efritz** [comment]
Fixed by b828f4d7a760dcddc51080cc201955a59b8da6d4.
